# -*- coding: utf-8 -*-
"""Problem_C4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1X3m5gbBHWnbKqUw3Vz-PvmTIh2gEP4FO
"""

# =====================================================================================================
# PROBLEM C4
#
# Build and train a classifier for the sarcasm dataset.
# The classifier should have a final layer with 1 neuron activated by sigmoid.
#
# Do not use lambda layers in your model.
#
# Dataset used in this problem is built by Rishabh Misra (https://rishabhmisra.github.io/publications).
#
# Desired accuracy and validation_accuracy > 75%
# =======================================================================================================

import json
import tensorflow as tf
import numpy as np
import urllib
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences


def solution_C4():
    data_url = 'https://github.com/dicodingacademy/assets/raw/main/Simulation/machine_learning/sarcasm.json'
    urllib.request.urlretrieve(data_url, 'sarcasm.json')

    # DO NOT CHANGE THIS CODE
    # Make sure you used all of these parameters or test may fail
    vocab_size = 1000
    embedding_dim = 16
    max_length = 120
    trunc_type = 'post'
    padding_type = 'post'
    oov_tok = "<OOV>"
    training_size = 20000

    with open("sarcasm.json", 'r') as file:
        data = json.load(file)

    sentences = []
    labels = []
    # YOUR CODE HERE
    for item in data:
        sentences.append(item['headline'])
        labels.append(item['is_sarcastic'])
    
    train_sentences = sentences[0:training_size]
    test_sentences = sentences[training_size:]
    train_labels = labels[0:training_size]
    test_labels = labels[training_size:]

    # Fit your tokenizer with training data
    tokenizer =Tokenizer(num_words=vocab_size,oov_token=oov_tok)
    tokenizer.fit_on_texts(train_sentences)
    word_index=tokenizer.word_index  # YOUR CODE HERE

    train_sequence=tokenizer.texts_to_sequences(train_sentences)
    train_padded=pad_sequences(train_sequence,maxlen=max_length, padding=padding_type, truncating=trunc_type)

    test_sequence=tokenizer.texts_to_sequences(test_sentences)
    test_padded=pad_sequences(test_sequence,maxlen=max_length, padding=padding_type, truncating=trunc_type)

    train_labels = np.array(train_labels)
    test_labels = np.array(test_labels)

    model = tf.keras.Sequential([
        tf.keras.layers.Embedding(vocab_size, embedding_dim, input_length=max_length),
        tf.keras.layers.GlobalAveragePooling1D(),
        tf.keras.layers.Dense(64, activation='relu'),
        tf.keras.layers.Dense(32, activation='relu'),
        # YOUR CODE HERE. DO not change the last layer or test may fail
        tf.keras.layers.Dense(1, activation='sigmoid')
    ])
    class MyThresholdCallback(tf.keras.callbacks.Callback):
      def __init__(self, threshold):
        super(MyThresholdCallback, self).__init__()
        self.threshold = threshold
      def on_epoch_end(self, epoch, logs=None):
          val_acc = logs["val_accuracy"]
          train_acc = logs["accuracy"]
          if val_acc > self.threshold and train_acc > self.threshold:
            self.model.stop_training = True

    callbacks = MyThresholdCallback(threshold=0.80)

    model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
    model.fit(train_padded, train_labels,
              epochs=100, callbacks = [callbacks],
              validation_data=(test_padded, test_labels), verbose=1)


    return model


# The code below is to save your model as a .h5 file.
# It will be saved automatically in your Submission folder.
if __name__ == '__main__':
    # DO NOT CHANGE THIS CODE
    model = solution_C4()
    model.save("model_C4.h5")

# -*- coding: utf-8 -*-
"""Problem_C4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RTpPdg_LOOC_Tg63A_XEYrJo9njWPNKY
"""

# =====================================================================================================
# PROBLEM C4
#
# Build and train a classifier for the sarcasm dataset.
# The classifier should have a final layer with 1 neuron activated by sigmoid.
#
# Do not use lambda layers in your model.
#
# Dataset used in this problem is built by Rishabh Misra (https://rishabhmisra.github.io/publications).
#
# Desired accuracy and validation_accuracy > 75%
# =======================================================================================================

import json
import tensorflow as tf
import numpy as np
import urllib
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences


def solution_C4():
    data_url = 'https://github.com/dicodingacademy/assets/raw/main/Simulation/machine_learning/sarcasm.json'
    urllib.request.urlretrieve(data_url, 'sarcasm.json')

    # DO NOT CHANGE THIS CODE
    # Make sure you used all of these parameters or test may fail
    vocab_size = 1000
    embedding_dim = 16
    max_length = 120
    trunc_type = 'post'
    padding_type = 'post'
    oov_tok = "<OOV>"
    training_size = 20000

    with open("sarcasm.json", 'r') as f:
        data = json.load(f)

    sentences = []
    labels = []
    for item in data:
        sentences.append(item['headline'])
        labels.append(item['is_sarcastic'])
    
    training_sentences = sentences[0:training_size]
    testing_sentences = sentences[training_size:]
    training_labels = labels[0:training_size]
    testing_labels = labels[training_size:]

    # Fit your tokenizer with training data
    tokenizer = Tokenizer(num_words=vocab_size, oov_token=oov_tok)
    tokenizer.fit_on_texts(training_sentences)
    word_index = tokenizer.word_index

    training_sequences = tokenizer.texts_to_sequences(training_sentences)
    training_padded = pad_sequences(training_sequences, maxlen=max_length, padding=padding_type, truncating=trunc_type)

    testing_sequences = tokenizer.texts_to_sequences(testing_sentences)
    testing_padded = pad_sequences(testing_sequences, maxlen=max_length, padding=padding_type, truncating=trunc_type)

    training_labels = np.array(training_labels)
    testing_labels = np.array(testing_labels)


    model = tf.keras.Sequential([
        # YOUR CODE HERE. DO not change the last layer or test may fail
        tf.keras.layers.Embedding(vocab_size, embedding_dim, input_length=max_length),
        tf.keras.layers.GlobalAveragePooling1D(),
        tf.keras.layers.Dense(64, activation='relu'),
        tf.keras.layers.Dense(32, activation='relu'),
        tf.keras.layers.Dense(1, activation='sigmoid')
    ])

    class MyThresholdCallback(tf.keras.callbacks.Callback):
      def __init__(self, threshold):
        super(MyThresholdCallback, self).__init__()
        self.threshold = threshold

      def on_epoch_end(self, epoch, logs=None): 
        val_acc = logs["val_accuracy"]
        train_acc = logs["accuracy"]
        if val_acc > self.threshold and train_acc > self.threshold:
          self.model.stop_training = True

    callbacks = MyThresholdCallback(threshold=0.75)

    model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
    model.fit(training_padded, training_labels,
              epochs=100, callbacks = [callbacks],
              validation_data=(testing_padded, testing_labels), verbose=2)
    
    return model

# The code below is to save your model as a .h5 file.
# It will be saved automatically in your Submission folder.
if __name__ == '__main__':
    # DO NOT CHANGE THIS CODE
    model = solution_C4()
    model.save("model_C4.h5")