# -*- coding: utf-8 -*-
"""Problem_B2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dK68Q09wxNfC3sI9eWDLrR81_9KtNer9
"""

# =============================================================================
# PROBLEM B2
#
# Build a classifier for the Fashion MNIST dataset.
# The test will expect it to classify 10 classes.
# The input shape should be 28x28 monochrome. Do not resize the data.
# Your input layer should accept (28, 28) as the input shape.
#
# Don't use lambda layers in your model.
#
# Desired accuracy AND validation_accuracy > 83%
# =============================================================================

import os
import tensorflow as tf
from tensorflow import keras

def solution_B2():
    fashion_mnist = tf.keras.datasets.mnist
    (x_train,y_train),_=fashion_mnist.load_data()
    # NORMALIZE YOUR IMAGE HERE
    x_train=x_train/255.0
    # Remember to inherit from the correct class
    class myCallback(tf.keras.callbacks.Callback):
      # Define the correct function signature for on_epoch_end
      def on_epoch_end(self, epoch, logs={}):
        if logs.get('accuracy') is not None and logs.get('accuracy') > 0.99: 
          print("\nReached 99% accuracy so cancelling training!") 
          # Stop training once the above condition is met
          self.model.stop_training = True
    # DEFINE YOUR MODEL HERE
    callbacks = myCallback()
    model = tf.keras.models.Sequential([ 
        keras.layers.Flatten(input_shape=(28, 28)),
        keras.layers.Dense(512, activation=tf.nn.relu),
        keras.layers.Dense(10, activation=tf.nn.softmax)
    ]) 
    # End with 10 Neuron Dense, activated by softmax

    # COMPILE MODEL HERE
    model.compile(optimizer='adam', 
                  loss='sparse_categorical_crossentropy', 
                  metrics=['accuracy']) 
    # TRAIN YOUR MODEL HERE
    history = model.fit(x_train, y_train, epochs=10, callbacks=[callbacks])

    return model

# The code below is to save your model as a .h5 file.
# It will be saved automatically in your Submission folder.
if __name__ == '__main__':
    # DO NOT CHANGE THIS CODE
    model = solution_B2()
    model.save("model_B2.h5")